### PR TITLE
Add optional config variables for email

### PR DESCRIPTION
**Pull request by tienne-B**
For instances that have problems with SendGrid, this commit will let people setup other providers/bypass the SendGrid add-on.

### CODE REVIEW

**Comment by philipbelesky** [comment]
Great, thanks for adding this. I don't have time to test at present, but just a note that we should make sure to check the different permutations (if you haven't already) during the next release candidate.

**Comment by tienne-B** [comment]
I was thinking about that, and I'd agree to use the conditional. However, SendGrid should be the `elif` condition here, as custom configuration should have priority over SendGrid configuration even if SendGrid variables are still present.

**Comment by czlee** [comment]
Sure. Either way, was just thinking it'd make more sense to treat them as mutually exclusive cases rather than a per-variable fallback.

**Comment by tienne-B** [comment]
To reopen this; could be useful to not limit admins with one service (SendGrid) over another.

**Comment by czlee** [comment]
Merging. Do we want to add docs? 🙂

**Pull request merged**
