### PR TITLE
Mark messages defined in Vue files for translation

### LINKED ISSUE #744: Finish translating strings in Vue templates
Strings provided by Vue templates do not seem to be translatable, of which is an omission of the i18n efforts. For consistency, these strings should use `gettext`.

### PR DESCRIPTION
**Pull request by tienne-B**
Check commit messages.

(There should also be a better way to handle these messages! ;) )

Closes #744.
~~Continues #1088 (therefore must be dealt with before this PR).~~ (Done)

### CODE REVIEW

**Comment by tienne-B** [comment]
@philipbelesky: For your attention (from commit message of 3177f08):

I did not mark the following message for translation (StatusContainer):

> "If you want to view this page without the sidebar (i.e. for
> displaying to an auditorium) you can <a :href="assistantUrl"
> target="_blank">open the assistant version.</a>"

as I am unsure of how it would be treated by gettext/Vue on account of
the hyperlink tag.

**Comment by philipbelesky** [comment]
@tienne-B hmm, I don't think there is the capacity for interpolation in this way within the translation framework. Perhaps we could re-write the setting along the lines of:

```
You can view this page without the sidebar, e.g. if displaying to an auditorium, 
by opening the assistant view.
<a href="LINK" v-text="gettext('Click here to open the assistant view.')"></a>
```

**Comment by tienne-B** [comment]
Also should I add the empty strings to the other languages' `.po` files?

**Comment by philipbelesky** [comment]
Yes that would be great, thanks!

**Comment by philipbelesky** [comment]
Thanks again for all your efforts in translating these!

**Comment by tienne-B** [comment]
Translating them comes later; I've only marked them for translation here ;p

**Pull request merged**
