### PR TITLE
Clarify speaker tab label

### PR DESCRIPTION
**Pull request by tienne-B**
As there is a different tab for reply speeches (without division classifiers), it makes more sense to use "Substantive speeches" (abbreviated to "Substantives") to describe that kind of tab.

Brings me to another question. How is (grammatical) gender dealt with in strings? Because if "All" is kept, there would have to be two different strings for that word in French: "toutes" for teams and "tous" for speakers.

### CODE REVIEW

**Comment by philipbelesky** [comment]
The 'All' here is designed to contrast with the category-specific pages that follow it — for instance 'novice' or 'ESL'. It is a bit awkwardly phrased, but I think calling it just 'Substantives' would remove the clarity between what distinguishes that page and the following categories. 

We could perhaps check if `speakercategory_set` has more than 0 results, and then use a 'All Categories' label; but use 'Substantives' in the case where there are none? That said 'Substantives' is a little awkward in categories without replies, such as BP, where there really isn't a distinction between substantive and non substantive.

**Comment by tienne-B** [comment]
Am I using the correct terminology though? I've always called them "Constructive speeches." I'll make the check.

**Comment by philipbelesky** [comment]
Its probably a regional difference — I think substantive is more common in areas that do 3vs3 in high school whereas constructive seems more america centric?

Also note that this page is also linked to from the admin sidebar and has its own titles — whatever name it should have should be consistent across those. I'm kind of leaning on just keeping the 'all' (perhaps all speakers + all teams?) — if we use substantive/constructive thats going to be less familiar to one particular region. This has also been what it has been called for many many years know so any update to the text might be more clear semantically but less clear for usability.

**Comment by tienne-B** [comment]
What the new patch does (`db7`...) is uses "Substantives" if there are reply speeches, and "All" otherwise. Categories are moved to be at the end, with an indicator "Categories."

**Comment by czlee** [comment]
For what it's worth, I think it's implicitly understood that "speaker tab" means "substantive speeches" unless otherwise indicated. Or, to go into more detail:

In university debating, "substantive"/"reply" vs "constructive"/"rebuttal" is a regional difference. It's also not just terminology—Asia and Oceania think of reply speeches a little differently to how North America thinks of rebuttal speeches. They're close enough to be analogous, but they're not the same. Also, as far as I'm aware, neither CP nor APDA score rebuttal speeches, so our reply speech feature isn't relevant to them. In Asians, Australs, Australian Easters and all New Zealand tournaments, it's quite well-understood that the "speaker tab" relates to substantive speeches—long before Tabbycat even existed.

My understanding is that WSDC is similar to Asia and Oceania on this, in terminology, purpose and scoring. But I'm not so familiar with the schools circuits.

**Comment by czlee** [comment]
Re grammatical gender, great question, @tienne-B—I've spent a lot of time trying to wrap my head around this (see #377).

In this particular case it's quite straightforward: We can provide a contextual marker, and `gettext` then considers two strings with different contexts to be distinct, and translated separately in the translation files. So it'd be like this:
```
{% trans "All" context "all [speakers]" %}
...
{% trans "All" context "all [teams]" %}
```

See: https://docs.djangoproject.com/en/2.1/topics/i18n/translation/#contextual-markers

In other contexts, where they're not conveniently standalone strings, this is another reason why DRY doesn't apply to human-readable strings, and more precisely why we try to avoid assembling sentences using concatenation where the word being substituted is one of a short list known ahead of time. In a purely hypothetical example: rather than `"All %(type)s"` with `type` being `"Speakers"` or `"Teams"`, you would enter `"All Speakers"` and `"All Teams"` as distinct strings.

**Comment by philipbelesky** [comment]
Ok, I've pushed up 474262eb30d294dbcb52b4a81e943f727516648b as some tweaks. Having played around with different formats, options I've thought worked best (for both menu and menu bar)

- For both teams and speaker standings, if there are no replies and no categories just use "Speakers" and "Teams" in the page menu and Speakers/Teams in the side menu.
- For both teams and speaker standings, if there are categories, use "All" in the page menu and "All Speakers" / "All Teams" in the side menu. I've removed the categories prefix because we are somewhat stretched for space here, and the category names are sufficiently obvious on their own. 
- If there are reply speeches, change from the previous option to use "Substantives" in the page menu (where there is a clarifying "Speakers" prefix) but retain "Speakers" in the side menu

This is a little ad hoc but I think employs the substantives vs replies distinction when it is needed and in formats where it should be relatively familiar. Let me know what you think and I'm happy to merge this after any further work on the grammatical gender issue.

**Pull request merged**
