### PR TITLE
Add classes for Email Message generators

### PR DESCRIPTION
**Pull request by tienne-B**
In an effort to reduce the amount of duplicated code, some inheritance is added to the execution of send_messages functions that are based on a queryset. This change will allow to mark those functions to be handled through Celery (background workers) in a later change.

### CODE REVIEW

**Comment by philipbelesky** [comment]
The inheritance patterns here look good. Is this ready to be merged, or are you still working on it?

**Comment by philipbelesky** [comment]
Ok cool, I'll try and find some time to look at the Celery branch also. No problem with Codeclimate — I never really give it more than a cursory glance. It's good to have it around but we don't really use it to vet PRs.

**Comment by tienne-B** [comment]
Your initial Celery setup is included in this PR. Don't think there's much (if anything) different in that branch.

**Comment by czlee** [comment]
Did we accidentally reverse the changes in #805 by merging this in?

**Pull request merged**
