### PR TITLE
README: Not limited to 3v3/BP formats

### PR DESCRIPTION
**Pull request by tienne-B**
Generalize to all parliamentary formats, but explicitly include British Parliamentary as it is quite distinct.

### CODE REVIEW

**Comment by philipbelesky** [comment]
I don't think that the use of 'parliamentary' here is common knowledge, or is at least less intuitive than saying "3vs3" or "2 team". For instance, I have no idea if Australs, much less many of the more obscure 3vs3 formats from NZ would count as 'parliamentary".

**Comment by tienne-B** [comment]
It is however the terminology we use in the project's description.

**Comment by philipbelesky** [comment]
I'd prefer to update the description text in that case, perhaps "Debating tabulation software for British Parliamentary and a variety of two-team formats"?

**Comment by tienne-B** [comment]
I'd be good with that, provided it's also reflected in the docs and README.

**Pull request closed without merging**
