### PR TITLE
Check for division by zero in feedback progress

### PR DESCRIPTION
**Pull request by tienne-B**
If no feedback is expected.

### CODE REVIEW

**Comment by tienne-B** [comment]
Sentry issue: [BACKEND-1AR](https://sentry.io/tabbycat-ig/backend/issues/884010864/?referrer=github_plugin)

**Comment by philipbelesky** [comment]
Thanks for the PR, and sorry for the delay in getting it merged!

**Comment by tienne-B** [comment]
Hotfix?

**Comment by philipbelesky** [comment]
That code doesn't seem to be in `master` — it looks to be a more simple method without division.

**Pull request merged**
