### PR TITLE
Add team data to ballot receipt

### LINKED ISSUE #845: Email Notification: Add additional information to ballot receipts
Thanks to @tienne-B for his hard work on bringing this excellent new feature to life. I was wondering if it would be helpful to add some additional information to the {{ scores }} variable. 

capture

It might be useful to include the total scores and ranking win/lose as well. I think judges are more likely to notice an issue here than by reading the individual speaker scores. This may be low priority given the work it might take to develop different display formats or may have intentionally not been done.

I can think of different ways to do this but one could possibly be:

BP: 
1st - CG: Sacred Heart 2 (180)
2nd - CO: St Andrews 2 (170)
3rd - OG: Macleans 2 (160)
4th - OO: St Marys 1 (140)

WSDC:
Winner - Proposition: Germany (250)
Loser - Opposition: France (245)

### PR DESCRIPTION
**Pull request by tienne-B**
This adds the team's ranking and total score to the ballot receipts for easier comparison. In addition, now the codes for sides are used to save on space.

Fixes #845.

### CODE REVIEW

**Comment by tienne-B** [comment]
And modifying the `as_dicts()` method causes upsets in the template code? I'm reluctant to change the method the data is collected as it would take more work, but also because I don't really understand the structure of `Scoresheet`, while the dictionary provides all the data needed.

**Comment by tienne-B** [comment]
Awaiting maintainer on this one; I need clarification on how to use the `Scoresheet` object. The structure baffles me a bit.

**Comment by czlee** [comment]
Sorry, now that I think about it we should've taken the opportunity to discuss this with a whiteboard this weekend. Is it mainly the object inheritance that's confusing? Or the purpose of particular methods? Are there particular bits of the docstrings that are confusing?

**Comment by tienne-B** [comment]
Think I've figured it out.

**Comment by philipbelesky** [comment]
Thanks for the PR! Have merged in with a minor change to the text that explicitly labels the team points vs speaks total.

**Pull request merged**
