### PR TITLE
Allow for multiple paragraphs in info-slides

### LINKED ISSUE #1002: Allow multiple paragraphs in info-slides
Some motions just need many paragraphs to explain. Currently, any line breaks are ignored.

### PR DESCRIPTION
**Pull request by tienne-B**
Fixes #1002.

~~How to get the Textarea to insert breaks without the form taking it as "Submit"?~~

### CODE REVIEW

**Comment by philipbelesky** [comment]
Hmm, it doesn't take it as submit for me, it just does nothing (Chrome/Safari, macOS). I'm not sure if thats due to the enter key being hijacked by form submission — could you try adding some javascript [similar to this comment](https://github.com/christianalfoni/formsy-react/issues/360#issuecomment-334991486) and see if that works?

**Comment by tienne-B** [comment]
No, that part was already done (the code you linked to was already present). What I was looking for was how to insert newlines in the text-area(s). Done in the last commit.

**Comment by philipbelesky** [comment]
Hey thanks for the update, I'd forgotten I had added the code in. This works as expected if the cursor is at the end of the text, however if you hit enter while in the middle of a paragraph the cursor then jumps to the end of the entire text block.

If I just comment out all the javascript on this page the form works as intended — it allows linebreaks (hitting enter doesn't submit the form). Is that the case on your end?

**Comment by tienne-B** [comment]
Removed the whole block.

**Comment by philipbelesky** [comment]
Great, thanks for looking into this. Feel free to add commits directly for change log updates related to these PRs btw.

**Comment by tienne-B** [comment]
Sure; hesitant as I don't really know the _grandeur_ necessary of a change to warrant inclusion in the CHANGELOG.

**Comment by tienne-B** [comment]
Done: 4182733de25dc49bf3cfe9a2b35067d0da369e31

**Pull request merged**
