### PR TITLE
replace context processor for menu selection with jquery

### PR DESCRIPTION
**Pull request by tfpk**
From: #580

### CODE REVIEW

**Comment by philipbelesky** [comment]
Hey thanks for adding this! The code that this remove was a particularly cumbersome hack, so great to have something much more elegant put in place instead.

**Comment by czlee** [comment]
Just wanted to echo what @philipbelesky said, this is great, thanks so much for doing it!

**Comment by czlee** [comment]
Just a heads-up, this changed the color of the links in this menu:

image

I don't think this is necessarily a bad thing, just checking if it was intentional?

**Comment by philipbelesky** [comment]
I think that was me in 471ea476400f1ebe600cd449985d11aa2e37c327, not in this PR. But yes those menu links in the drop downs should now match the general top-menu.

**Pull request merged**
