### PR TITLE
Add inheritance to Email factories

### PR DESCRIPTION
**Pull request by tienne-B**
Part of #740. Should not be merged right now. The private URL messages can be tested; but I haven't gotten them to work quite yet (but fixed all the serialization stuff).

### CODE REVIEW

**Comment by tienne-B** [comment]
Well, doesn't seem like it was Celery's problem; doesn't work without it either :)

**Comment by tienne-B** [comment]
Without the new classes, serialization is the main problem, as it seems only querysets can be serialized, not objects on its own or the dictionary generator of `DebateResult`.

**Comment by philipbelesky** [comment]
Hmm what format are you serialising to? We have a few custom serialisers as model methods for creating JSON, would a similar approach work if the standard dictionary conversion is not working?

**Comment by tienne-B** [comment]
For the ballot receipts, I tried with both Celery's serializer (which gave me a `'generator` is not serializable`) and Django's one. Where are TC's custom serializers?

**Comment by philipbelesky** [comment]
There are a bunch in `partcipants/models` if you search for `serialize`. Some of these could probably use standard serializers but they make working with the resulting JSON easier. Not sure if these are applicable in this case, I'll try and look into the changes to see what kind of serializer Celery wants if I have the time.

**Comment by tienne-B** [comment]
Getting nowhere. I'd be happy if @philipbelesky finds something but I'll close the PR for now.

**Pull request closed without merging**
