### PR TITLE
Add link for participant self-check-in

### LINKED ISSUE #684: Participant check-in could be done by the individuals
This may also be a contentious feature, but having participants check themselves in could be added. With the live views of check-ins (even with the "assistant" view which is also for display), instructions for self-check-ins could be shown, with officials overriding and complementing this self-system. Of course there would be settings to enable this feature.

There are two methods I thought of for it:
* **Inbound email**: Participants will be requested to send a message (say `!checkin`) to the sendgrid email address (which does take inbound messages). Then, the linked participant to the email gets their status updated live (or with a reply). Un-linked addresses could get a reply indicating its failure.
* **Private URLs**: A page for each participant/team with a simple "Check-in" button is created using their related private URLs. Pressing it updates (toggles?) their status.

Both these methods would take the timeframe into account for rejections.

### PR DESCRIPTION
**Pull request by tienne-B**
Adds the participant check-in button to their splash page. Fixes #684.

### CODE REVIEW

**Comment by tienne-B** [comment]
The difficulty I'm having is that the label of the button does not consistently update after being pressed, nor does the success message appear. I'd appreciate suggestions to resolve that.

**Comment by philipbelesky** [comment]
Hmm, just looking at the code the success message looks like it should be appearing. I'll hopefully be able to pull locally and check soon. In terms of the button updating, do you mean that it updates after it is clicked (to show some loading state) or that it doesn't update to reflect the changed state once someone has been redirected back to that page?

**Comment by tienne-B** [comment]
The button text should change from "Check-in" to "Sign-out."

**Comment by philipbelesky** [comment]
Hey @tienne-B just a quick note that I pushed up two commits here that fix the button text issue (and the underlying issue) as well as a few other fixes. The commit descriptions have a more detailed set of changes — let me know if you had any questions about them. And thanks again for the PR!

**Comment by tienne-B** [comment]
Didn't solve the issue. The messages are shown on the next page the person visits, and the text does not update.

**Comment by tienne-B** [comment]
Please see #701 for the proper fix.

**Pull request merged**
