### PR TITLE
Corrections to strings

### PR DESCRIPTION
**Pull request by tienne-B**
See commit messages.

### CODE REVIEW

**Comment by philipbelesky** [comment]
My first though that more explicit var names, i.e. `round_name` over 'name' would be preferred, but happy to defer here given you are much more involved in translation.

**Comment by tienne-B** [comment]
My point was to have explicit yet consistent variable names, so remove the `_name` suffix to keep `round` from `round_name`, not the opposite! Different places used those three variations (and others...)

**Comment by czlee** [comment]
The reason the variable name `round` wasn't used was to avoid conflict with the variable `round` that the context processor sets:

https://github.com/TabbycatDebate/tabbycat/blob/74622b05a150cdf4a1441e0212e2824840033cd9/tabbycat/utils/context_processors.py#L17-L26

While it might not have practical effect on some _particular_ page to overwrite this context variable, I'd still prefer to avoid variable naming conflicts in templates as a matter of good practice.

**Comment by tienne-B** [comment]
From my tests and the documentation, the (re-)definition of template variables have the scope of the block tag, and becomes « normal » again afterwards. Am I wrong in that?

**Comment by czlee** [comment]
I actually think it's bad practice to have two variables with the same name, even if the scope of one is more local than the other, because it can be confusing. So I prefer to avoid having to ask the question you just did in the first place. (It's fine if they're in two disjoint scopes.)

**Pull request merged**
