### PR TITLE
Reconcile emoji list with spreadsheet

### PR DESCRIPTION
**Pull request by tienne-B**

### CODE REVIEW

**Comment by tienne-B** [comment]
You're welcome, @philipbelesky ;p

**Comment by philipbelesky** [comment]
Thanks! There are a few cases where I need to re-reconcile things as the PR updates changes in the source but not the spreadsheet. These are, of course, my own fault but I'm going to leave this PR open to make sure I don't forget to do so.

**Comment by tienne-B** [comment]
Like where?

**Comment by philipbelesky** [comment]
Just a few of the labels I think, where they were shortened, i.e. "Wearing Sunglasses" > "Sunglasses"

**Comment by tienne-B** [comment]
I made those changes as there were name conflicts. (Wearing Sunglasses conflicted with the Dark Sunglasses emoji)

**Comment by philipbelesky** [comment]
Ah right, that makes sense. I'll make a note to go through and check them a little closer to 2.3 being released then.

**Pull request merged**
