### PR TITLE
Give all participants a private URL

### PR DESCRIPTION
**Pull request by tienne-B**
Sorry for this huge PR, couldn't neatly divide the commit due to DB migrations. (Also mostly worked on it in the plane...) The `Person` table now has a field for `Tournament` as well as for the private URL.

This commit does the side-discussion from #684, and checkins will be added in another commit (separated that at least :) )

Check the commit message for more details.

### CODE REVIEW

**Comment by tienne-B** [comment]
Is there a particular way to update the `fixtures`? Doing a `loaddata`/`dumpdata` gives a somewhat different form than what was there.

**Comment by philipbelesky** [comment]
The method I use is:

'python manage.py loaddata data/fixtures/completed_demo.json'

[do migrations and stuff]

'python manage.py dumpdata --natural-foreign --natural-primary -e options -e sessions -e contenttypes --format=json -o data/fixtures/completed_demo.json'

**Comment by czlee** [comment]
Just commenting for clarity that my thoughts are in #684 (where they seem to flow better with existing discussion)

**Comment by tienne-B** [comment]
@philipbelesky: May I have more details on your method here? I think you're missing `-e auth.permission` first of all but what JSON formatter do you use?

Split the private URL feedback view in two so that `self.get_object()` works. That was the stumbling block that prompted me to move `Tournament` to `Person`.

**Comment by czlee** [comment]
@tienne-B Actually, I wrote a script that migrates the fixtures, it's called `migrate_fixtures.py` and it's under the `data` directory. The script is based on @philipbelesky's method. It'll migrate to the old commit's schema, load the fixture, then check out the new commit and migrate to the new commit's schema, then replace the fixture. The one important thing I should point out is that you should set up a blank, **unmigrated** database before you start it, and point your local settings file to it.

Let me know if it doesn't work. It auto-detects most things, but it's not perfect, and I'm definitely keen to patch it if it fails.

**Comment by czlee** [comment]
Oh! Fair enough. The `--indent=4` part actually isn't mandatory—JSON is valid if the whole file has not a single newline—but I put it in the script so that git-diffs would show in some sensible manner, since git-diffs run line by line. I'll make a note to add this information to the contributing docs.

**Comment by czlee** [comment]
I was just thinking about the [data migration](https://docs.djangoproject.com/en/2.0/topics/migrations/#data-migrations) for this, and realized it's not obvious. I mean, half of it is obvious—every adjudicator's URL key should be copied to the corresponding `Person`. But there's a uniqueness constraint on URL keys, which means we can't copy every team's URL key to the two or more speakers on the team. Probably the least bad thing we could do is just choose any _one_ speaker on the team to copy the team's URL key to, and leave the other speakers blank?

@tienne-B Do you want to have a crack at the data migration? I'd be happy to do it but wanted to give you first dibs. Here's a (not very analogous) example: [participants/migrations/0016_populate_team_names.py from version 1.4.6](https://github.com/TabbycatDebate/tabbycat/blob/v1.4.6/tabbycat/participants/migrations/0016_populate_team_names.py). (We ran a giant squash in version 2.0 so we don't have many data migrations in our current code base.)

**Comment by tienne-B** [comment]
The migration now moves the data, including to a speaker on each team.

**Pull request merged**
