### PR TITLE
Don't select people with duplicates by default

### PR DESCRIPTION
**Pull request by tienne-B**
This commit adds filters for participants for who to select by default to exclude participants who have already been sent a notification of the same type in the same tournament/round.

### CODE REVIEW

**Comment by philipbelesky** [comment]
Hmm, what happens here if I want to send out a second set of emails to update information that was incorrect earlier? I.E. if I forgot to allocate venues before emailing the draw? 

This seems like it might be a bit of a 'magic' behaviour that could be confusing as compared to the lesser annoyance of just receiving two emails.

**Comment by tienne-B** [comment]
Good point. The idea is that for most situations where re-sending messages is warranted, it would only be for a subset of the potential recipients, of who would probably be remembered. Having everyone (or most) selected would not be wanted (but I do see your situation, and am disappointed that JSON fields can't be compared)

**Comment by philipbelesky** [comment]
Ah right, I think that makes sense and the tables make it pretty clear who each email is going to. If there is a need to provide new data its probably either a case of sending to a very small number of people or sending to *everyone*. The table accommodates either option pretty well.

**Comment by tienne-B** [comment]
Has there been a change in the selection table code? It now shows "No changes" and not the selection options (works in the old branch though)

**Comment by philipbelesky** [comment]
Sorry, which table should I be looking at? And by selection code do you mean the buttons for All/None that toggle the checkboxes?

**Comment by tienne-B** [comment]
The people selection table (any of them; private URLs email as example)
Yes, the buttons for All/None. Also the button indicating changes. Odd regression...

**Comment by philipbelesky** [comment]
Yup, that's the problem. See 135cc2beeaec94f0eabee30e35991972efb3f05f for the solution (it was caused by a template inheritance issue). Also as an FYI if you use Chrome for development the Vue.js devtools extension will make debugging a lot easier.

**Pull request merged**
