### PR TITLE
Remove ignored feedback ratings from adj scores

### LINKED ISSUE #1026: Ignored feedback appears to still contribute to adjudicator average
Just a small thing from a recent tournament; when certain pieces of feedback were marked in the admin interface as 'ignored', the adjudicator's metrics did not update to reflect that (ie. the ignored score was still counting towards their numbers).

### PR DESCRIPTION
**Pull request by tienne-B**
Sort-of the whole point of ignoring feedback...

Candidate for hotfix
Fixes #1026.

### CODE REVIEW

**Comment by philipbelesky** [comment]
Thanks for the PR and the quick turn around! Definitely should have added a test for this case :/

**Comment by tienne-B** [comment]
I thought I had!

**Comment by philipbelesky** [comment]
Oh sorry, I thought the original ignore function was added before your contributions which were to add the unconfirmed state as an additional option (or vice versa?).

**Comment by tienne-B** [comment]
Vice versa. #538 (issue) & #629 (PR)

**Pull request merged**
